### ISSUE TITLE
Err:504 in All Cells

### ISSUE THREAD

**Issue by rkcf** [cmallwitz/Financials-Extension#7]
When opening the example sheet, all GETREALTIME & GETHISTORIC formula cells return a 504 error. I have tried restarting libreoffice, and reinstalling the extension. There are no diagnostics on the "Support" sheet. The extension did create the `~/.financials-extension` directory, but it is empty.

System specs:
```
ArchLinux 5.8.1-arch1-1 x86_64 GNU/Linux
LibreOffice 6.4.5.2
Financials-Extension 2.1.0
python 3.8.5
python-dateutil 2.8.1
pytz 2020.1
pyparsing 2.4.7
```

**Comment by cmallwitz** [comment]
Have you tried selecting a different source (other than Yahoo) in the first sheet? I woul need to set up a VM to take a closer look at ArchLinux.

**Comment by cmallwitz** [comment]
Actually there was a cookie related issue with Yahoo. I have fixed it and released a new version 2.1.1. Let me know if that works better for you.

**Comment by rkcf** [comment]
I tried with the updated version. Still have the same issue. I am going to try and build the extension from scratch and see if I can figure anything out. I'll post my findings later.

**Comment by cmallwitz** [comment]
Odd... If you have the code locally you could run the tests too. With the "src" directory your current working directory, just run e.g. "python3 test_google.py" (this should work even if you don't actually build anything because you don't have the LibreOffice SDK installed)

**Comment by triyanwn** [comment]
It seems the problem is on the google module. 

I run `python3 test_yahoo.py` and I got the following output:
<pre>
Traceback (most recent call last):
  File "test_yahoo.py", line 23, in <module>
    financials = financials.createInstance(None)
  File "/home/bie/Financials-Extension-master/src/financials.py", line 244, in createInstance
    return FinancialsImpl(ctx)
  File "/home/bie/Financials-Extension-master/src/financials.py", line 82, in __init__
    self.google = google.createInstance(ctx)
AttributeError: module 'google' has no attribute 'createInstance'
</pre>

I commented out line 82 of `financials.py`, and now `python3 test_yahoo.py` return the following output:
<pre>
.....2020-12-23 23:30:25,470 yahoo ERROR HttpException ticker=NO_NAME datacode=21 date=2018-01-08
Traceback (most recent call last):
  File "/home/bie/Financials-Extension-master/src/yahoo.py", line 315, in getHistoric
    text = self.urlopen(url)
  File "/home/bie/Financials-Extension-master/src/baseclient.py", line 178, in urlopen
    raise HttpException(url, self.response.status)
baseclient.HttpException: ('https://query1.finance.yahoo.com/v7/finance/download/NO_NAME?period1=1512662400&period2=1608741025&interval=1d&events=history&crumb=mDrp.sx8Z0O', 404)
.......
----------------------------------------------------------------------
Ran 12 tests in 24.114s

OK
</pre>
 
I can install it on LibreOffice, and it fetches the data correctly from Yahoo and Financial Times. 

I know nothing about Python, so I can't investigate further.

**Comment by cmallwitz** [comment]
This is really odd indeed but I have recently released a new version (2.3.0) that has better handling/logging of exceptions and works better in non-English user environments. Could you give it a try? Please download the latest version from the Release section or pull latest version from GitHub.

**Comment by triyanwn** [comment]
I have tried version 2.3.0, and I still got Err:504 in all cells.

I think the problem is the file name of `google.py`. Maybe Python in Arch try to import the [google module](https://pypi.org/project/google/) from system wide, even though the module is not installed.

I rename it to `gfinance.py`, and change all the occurrence of `google` to `gfinance` in `financials.py` and `compile.sh`. Then I can compile and install the extension to LibreOffice, and now it fetches the data correctly from Yahoo, FT and Google.

Thanks for this excellent extension 👍

**Comment by cmallwitz** [comment]
That is actually a good point. Maybe my google/yahoo/ft modules are names a bit too generically and clash with other stuff installed - on my system I wouldn't be able to tell what modules are installed possibility as dependency of something else. Not without having some indication of something broken and then looking for it specifically.

Let me create a new version with more descriptive module names to avoid clashes in future.

Thanks!

**Comment by cmallwitz** [comment]
I published a new version 2.4.0 with renamed files - let me know if that works for you.

**Comment by triyanwn** [comment]
Yes, version 2.4.0 works as expected. Thanks!
